; ============================================================
;  Desklight Robot — PlatformIO project
;  Target: Arduino MEGA ADK (ATmega2560)
; ============================================================
[env:megaADK]
platform  = atmelavr
board     = megaadk
framework = arduino

; USB Host Shield 2.0 + USBH_MIDI
; Registry name uses "USB-Host-Shield-20" (no dot)
lib_deps =
    felis/USB-Host-Shield-20

; Serial monitor speed (UART0)
monitor_speed = 115200

build_flags =
    -DARDUINO_AVR_ADK       ; makes USB Host Shield pick the right SS pin
    -DUSB_HOST_SHIELD_USE_ISR=0
